name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        cd ipof
        go mod tidy

    - name: Build the project
      run: |
        cd ipof
        go build -v ./...

    - name: Run tests
      run: |
        cd domaintoip
        go test -v ./...
        
    - name: Verify formatting
      run: |
        cd ipof
        go fmt ./...

    - name: Lint the code
      run: |
        cd ipof
        go vet ./...